export const featuredSites = [
  {
    name: "Earnlab",
    tagline: "Highest paying GPT site with multiple offerwalls",
    bonus: "Gamdom +25% — Use code NETROX",
    logo_url: new URL("../imgs/Sites/earnlab.png", import.meta.url).href,
    visit_url: "https://earnlab.com/r/netrox",
    bonus_tag: "Gamdom +25%",
    rank: 1,
    rating: 5,
    features: ["Instant payments", "Sign up bonus", "Referral program", "Worldwide"],
    details: { pay_time: "A few minutes", min_withdraw: "$0.50", min_age: "16" },
    rewards: ["PayPal", "Bitcoin", "Litecoin", "Gift Cards", "Gamdom"],
  },
  {
    name: "CoinPayU",
    tagline: "80-85% Rates - High Bonuses/Leaderboards and instant payouts",
    logo_url: new URL("../imgs/Sites/coinpayu.gif", import.meta.url).href,
    visit_url: "https://www.coinpayu.com/?r=Netrox",
    rank: 2,
    rating: 5,
    features: ["High site bonuses", "Many offerwalls", "Fast payments", "Worldwide"],
    details: { pay_time: "Within 24 hours", min_withdraw: "$0.50", min_age: "16" },
    rewards: ["PayPal", "Bitcoin", "Litecoin", "Gift Cards"],
  },
  {
    name: "GemsLoot",
    tagline: "Exclusive Offers - Instant Cashouts - 65-95% Rates",
    logo_url: new URL("../imgs/Sites/gemsloot.jpg", import.meta.url).href,
    visit_url: "https://gemsloot.com/?aff=netrox",
    bonus_tag: "Roobet +20%",
    rank: 3,
    rating: 5,
    features: ["Instant payments", "Sign up bonus", "Referral program", "Worldwide"],
    details: { pay_time: "Within 12 hours", min_withdraw: "$0.50", min_age: "16" },
    rewards: ["PayPal", "Bitcoin", "Litecoin", "Amazon", "Roobet"],
  },
  {
    name: "CashInStyle",
    tagline: "$2 bonus after earning $10 - 90% rates on all offerwalls",
    logo_url: new URL("../imgs/Sites/cis.svg", import.meta.url).href,
    visit_url: "https://cashinstyle.com/?ref=NETROX",
    rank: 4,
    rating: 5,
    features: ["Instant payments", "Sign up bonus", "Referral program", "Worldwide"],
    details: { pay_time: "24 hours", min_withdraw: "$2.00", min_age: "16" },
    rewards: ["PayPal", "Bitcoin", "Litecoin", "Gift Cards"],
  },
  {
    name: "Earnopolis",
    tagline: "85% Rates - Fast cashouts & exclusive offers",
    logo_url: new URL("../imgs/Sites/earnopolis.webp", import.meta.url).href,
    visit_url: "https://earnopolis.com/r/?r=netrox",
    rank: 5,
    rating: 4,
    features: ["Fast payments", "Sign up bonus", "Referral program", "Worldwide"],
    details: { pay_time: "1-3 hours", min_withdraw: "$1.00", min_age: "16" },
    rewards: ["PayPal", "Bitcoin", "Gift Cards"],
  },
];

export const allOfferwalls = [
  "adgate", "adscend", "adtowall", "ayetstudios", "bitlabs", "gemiad",
  "hangmyads", "lootably", "mmwall", "monlix", "myChips",
  "notik", "primeearn", "pixylabs", "revu", "timewall", "torox", "waxrewards",
];

export const allSites = [
  { name: "Earnlab", description: "80-90% Rates | Highest Paying Website", logo_url: new URL("../imgs/Sites/earnlab.png", import.meta.url).href, visit_url: "https://earnlab.com/r/netrox", badge: "top1", bonus_tag: "Gamdom +25%", rating: 5, rates: 90, offerwalls: ["primeearn", "torox", "ayetstudios", "revu", "adscend", "adgate", "adtowall", "mmwall", "hangmyads", "lootably", "monlix"] },
  { name: "CoinPayU", description: "80-85% Rates | High Site Bonuses & Leaderboards", logo_url: new URL("../imgs/Sites/coinpayu.gif", import.meta.url).href, visit_url: "https://www.coinpayu.com/?r=Netrox", badge: "top2", rating: 5, rates: 85, offerwalls: ["primeearn", "adgate", "torox", "ayetstudios", "mmwall", "hangmyads", "lootably", "bitlabs", "timewall", "monlix"] },
  { name: "GemsLoot", description: "65-95% Rates | Instant Cashouts & Exclusive Offers", logo_url: new URL("../imgs/Sites/gemsloot.jpg", import.meta.url).href, visit_url: "https://gemsloot.com/?aff=netrox", badge: "top3", bonus_tag: "Roobet +20%", rating: 5, rates: 75, offerwalls: ["primeearn", "torox", "ayetstudios", "revu", "adscend", "adgate", "gemiad", "adtowall", "mmwall", "hangmyads", "lootably", "waxrewards", "pixylabs"] },
  { name: "CashinStyle", description: "90% Rates | Highest Paying Offerwalls", logo_url: new URL("../imgs/Sites/cis.svg", import.meta.url).href, visit_url: "https://cashinstyle.com/?ref=NETROX", badge: "top4", rating: 5, rates: 90, offerwalls: ["primeearn", "torox", "ayetstudios", "revu", "adscend", "adgate", "gemiad", "adtowall", "mmwall", "hangmyads", "lootably"] },
  { name: "Earnopolis", description: "85% Rates | Fast Cashouts & Exclusive Offers", logo_url: new URL("../imgs/Sites/earnopolis.webp", import.meta.url).href, visit_url: "https://earnopolis.com/r/?r=netrox", badge: "top5", rating: 5, rates: 85, offerwalls: ["primeearn", "torox", "myChips", "ayetstudios", "adscend", "timewall"] },
  { name: "Casheo", description: "70% Rates | 5$ SignUp BONUS", logo_url: new URL("https://casheo.co/logo-icon.svg?dpl=dpl_5jR9S87ceMsvZYsHSedvWscehCy6").href, visit_url: "https://casheo.co/r/netrox", badge: "new", rating: 5, rates: 70, offerwalls: ["notik", "ayetstudios", "adscend", "revu", "torox", "monlix", "bitlabs", "lootably"] },
  { name: "SharkEarnings", description: "65% Rates | Multi-Offerwall Coverage", logo_url: "https://www.google.com/s2/favicons?domain=sharkearnings.com&sz=128", visit_url: "https://sharkearnings.com/r/netrox", badge: "new", rating: 5, rates: 65, offerwalls: ["torox", "myChips", "gemiad", "bitlabs", "mmwall", "adscend", "notik", "pixylabs", "monlix"] },
  { name: "GotKash", description: "75% Rates", logo_url: "https://www.google.com/s2/favicons?domain=gotkash.com&sz=128", visit_url: "https://gotkash.com/r/Netrox", badge: "new", rating: 5, rates: 75, offerwalls: ["ayetstudios", "notik", "torox", "adscend", "gemiad", "adtowall", "lootably", "hangmyads"] },
  { name: "RewardFlow", description: "New GPT Site | Multiple Offerwalls", logo_url: new URL("../imgs/Sites/rewardflow.png", import.meta.url).href, visit_url: "https://rewardflow.me/?ref=NETROX", badge: "new", rating: 5, rates: 80, offerwalls: ["torox", "adscend", "notik", "timewall", "adtowall", "lootably", "mmwall", "gemiad"] },
  { name: "DollvCash", description: "85% Rates | New GPT Site", logo_url: "https://dollvcash.com/assets/logo-TZyamRuA.png", visit_url: "https://dollvcash.com/r/H9IgcL", badge: "new", rating: 5, rates: 85, offerwalls: ["gemiad", "adtowall", "torox", "notik", "pixylabs", "monlix", "ayetstudios", "timewall", "adscend"] },
  { name: "CashInBucks", description: "80% Rates | New GPT Site", logo_url: "https://cashinbucks.com/public/Frontend/dashboard/img/CashinBucks_logo_icon_logo.png", visit_url: "https://cashinbucks.com/?ref=netrox", badge: "new", rating: 5, rates: 80, offerwalls: ["gemiad", "adtowall", "notik", "pixylabs"] },
  { name: "FreeCoin", description: "70% Rates | New Site by Splitdrop", logo_url: "https://freecoin.ai/images/web_header_logo.svg", visit_url: "https://freecoin.ai/home.html?friend=5615", badge: "new", rating: 5, rates: 70, offerwalls: ["torox", "revu", "myChips", "hangmyads"] },
  { name: "MoonMiles", description: "80% Rates | Fast Cashouts", logo_url: new URL("../imgs/Sites/moonmiles.png", import.meta.url).href, visit_url: "https://moonmiles.io/r/netrox", badge: "popular", rating: 5, rates: 80, offerwalls: ["torox", "revu", "ayetstudios", "adtowall", "lootably", "adscend"] },
  { name: "CashTask", description: "85% Rates on Offerwalls | Instant Cashouts", logo_url: new URL("../imgs/Sites/cashtask.webp", import.meta.url).href, visit_url: "https://cashtask.net/r/47CWX93", badge: "popular", rating: 5, rates: 85, offerwalls: ["gemiad", "waxrewards", "lootably", "adtowall", "monlix", "notik", "mmwall"] },
  { name: "Chequity", description: "80% Rates | Simple Website", logo_url: new URL("../imgs/Sites/cheq.png", import.meta.url).href, visit_url: "https://chequity.io/r/128BDC40", badge: "popular", rating: 5, rates: 80, offerwalls: ["torox", "ayetstudios", "revu", "adscend", "adgate", "gemiad", "adtowall", "mmwall", "hangmyads", "lootably", "waxrewards"] },
  { name: "CashEarn", description: "80% Rates | Fast Cashouts", logo_url: new URL("../imgs/Sites/cashearn.webp", import.meta.url).href, visit_url: "https://cashearn.gg/r/8L3D1M7", badge: "popular", rating: 5, rates: 80, offerwalls: ["gemiad", "waxrewards", "myChips", "adtowall", "ayetstudios", "lootably", "notik"] },
  { name: "RBXFast", description: "80% Rates", logo_url: new URL("../imgs/Sites/rbxfast.webp", import.meta.url).href, visit_url: "https://rbxfast.com/r/netrox", badge: "popular", rating: 5, rates: 80, offerwalls: ["gemiad", "adtowall", "waxrewards", "adscend", "lootably", "monlix", "myChips"] },
  { name: "Gain.gg", description: "70-80% Rates | Instant Cashouts", logo_url: new URL("../imgs/Sites/gain.png", import.meta.url).href, visit_url: "https://gain.gg/r/netrox", badge: "popular", rating: 5, rates: 80, offerwalls: ["adgate", "primeearn", "adtowall", "torox", "lootably", "myChips", "ayetstudios", "adscend", "revu"] },
  { name: "Pawns", description: "85% Rates | Strong Offerwall Coverage", logo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfUS8t48RNND8suutXMQHX6s01TuLHkgUlMw&s", visit_url: "https://pawns.app/?r=19345226", badge: "mobile_app", rating: 5, rates: 85, offerwalls: ["primeearn", "bitlabs"] },
  { name: "PrimeOpinion", description: "85% Rates | Only Prime Earn", logo_url: "https://www.google.com/s2/favicons?domain=primeopinion.com&sz=128", visit_url: "https://primeopinion.com/register?ref=a08ed474-82c3-45d0-abbf-7bf64f2e0072", badge: "mobile_app", rating: 5, rates: 85, offerwalls: ["primeearn"] },
  { name: "RustClash", description: "95% Rates | Only Prime Earn", logo_url: "https://www.google.com/s2/favicons?domain=rustclash.com&sz=128", visit_url: "https://rustclash.com/r/NETROX", bonus_tag: "Casino", rating: 5, rates: 95, offerwalls: ["primeearn"] },
  { name: "AceBet", description: "95% Rates | Only Prime Earn", logo_url: "https://www.google.com/s2/favicons?domain=acebet.co&sz=128", visit_url: "https://acebet.co/welcome/r/netrox", bonus_tag: "Casino", rating: 5, rates: 95, offerwalls: [] },
  { name: "HeyCash", description: "75% Rates | Prime Earn Offers", logo_url: "https://www.google.com/s2/favicons?domain=heycash.com&sz=128", visit_url: "https://heycash.com/register?ref=9d0e3270-4a7e-42b5-b7f4-94c5c3af7bfd", rating: 5, rates: 75, offerwalls: ["primeearn"] },
  { name: "SuperpayMe", description: "70% Rates | Multi-Offerwall Coverage", logo_url: "https://www.google.com/s2/favicons?domain=superpay.me&sz=128", visit_url: "https://superpay.me/?ref=1774518509", rating: 5, rates: 70, offerwalls: ["primeearn", "revu", "adtowall", "myChips"] },
  { name: "EarnX", description: "70% Rates", logo_url: new URL("../imgs/Sites/earnx.png", import.meta.url).href, visit_url: "https://earnx.gg/r/netrox", rating: 5, rates: 70, offerwalls: ["adscend", "bitlabs", "gemiad", "torox", "myChips", "notik", "monlix", "lootably"] },
  { name: "FeaturePoints", description: "70% Rates | Mobile App", logo_url: "https://www.google.com/s2/favicons?domain=featurepoints.com&sz=128", visit_url: "https://featurepoints.com/@netrox", badge: "mobile_app", rating: 5, rates: 70, offerwalls: ["torox", "ayetstudios", "revu"] },
  { name: "Idle Empire", description: "Offerwall Variety | Trusted GPT Platform", logo_url: "https://www.google.com/s2/favicons?domain=idle-empire.com&sz=128", visit_url: "https://www.idle-empire.com?r=netrox", rating: 5, offerwalls: ["revu", "adgate", "lootably", "adscend", "torox", "gemiad", "myChips"] },
  { name: "Scrambly", description: "Exclusive Offers | Instant Cashout", logo_url: new URL("../imgs/Sites/scrambly_ logo.jpg", import.meta.url).href, visit_url: "https://go.scrambly.io/ao1aoE", badge: "mobile_app", rating: 5, rates: 50, offerwalls: [] },
  { name: "Pengu Pace", description: "Exclusive Offers | Instant Cashout", logo_url: new URL("../imgs/Sites/pengu.png", import.meta.url).href, visit_url: "https://go.scrambly.io/kPE2RU", badge: "mobile_app", rating: 5, rates: 50, offerwalls: [] },
  { name: "FastAsk", description: "100% Rates on WaxRewards", logo_url: new URL("../imgs/Sites/fastask.png", import.meta.url).href, visit_url: "https://fastask.net/?ref=296", rating: 5, rates: 100, offerwalls: ["waxrewards", "lootably", "myChips"] },
  { name: "EarnLoop", description: "85% Rates | Fast Cashouts", logo_url: new URL("../imgs/Sites/earnloop.svg", import.meta.url).href, visit_url: "https://earnloop.net/r/YLNMXR5KWR", rating: 5, rates: 85, offerwalls: ["adgate", "adtowall", "torox", "lootably", "myChips", "ayetstudios", "adscend", "revu"] },
  { name: "Giftably", description: "80% Rates", logo_url: new URL("../imgs/Sites/giftably.webp", import.meta.url).href, visit_url: "https://giftably.net/login/Lucas", rating: 5, rates: 80, offerwalls: [] },
  { name: "RewardXP", description: "80% Rates", logo_url: new URL("../imgs/Sites/rewardxp.png", import.meta.url).href, visit_url: "https://www.rewardxp.com/join/1425421", rating: 5, rates: 80, offerwalls: ["torox", "timewall", "myChips", "adscend", "ayetstudios"] },
  { name: "PrizeRebel", description: "50% Rates", logo_url: "https://www.google.com/s2/favicons?domain=prizerebel.com&sz=128", visit_url: "https://www.prizerebel.com/index.php?r=16500529", rating: 5, rates: 50, offerwalls: ["revu", "myChips", "adscend", "ayetstudios", "torox", "adgate"] },
  { name: "PollPay", description: "80% Rates", logo_url: "https://www.google.com/s2/favicons?domain=pollpay.app&sz=128", visit_url: "https://www.pollpay.app?rb=208011612", badge: "mobile_app", rating: 5, rates: 80, offerwalls: ["adgate"] },
  { name: "PrizeBear", description: "80% Rates", logo_url: new URL("../imgs/Sites/prizebear.png", import.meta.url).href, visit_url: "https://prizebear.com/r/uWEzvO", rating: 5, rates: 80, offerwalls: ["adgate", "adtowall", "torox", "lootably", "myChips", "ayetstudios", "adscend", "revu"] },
  { name: "Sparkvey", description: "80% Rates", logo_url: new URL("../imgs/Sites/sparkvey.ico", import.meta.url).href, visit_url: "https://sparkvey.com/?ref=netrox", rating: 5, rates: 80, offerwalls: ["adgate", "adtowall", "torox", "lootably", "myChips", "ayetstudios", "adscend", "revu"] },
  { name: "Cash Center", description: "75% Rates | Timewall + Notik Offers", logo_url: "https://www.google.com/s2/favicons?domain=cash-center.fun&sz=128", visit_url: "https://cash-center.fun/ref/45d492d1", rating: 5, rates: 75, offerwalls: ["timewall", "notik"] },
  { name: "GameHag", description: "80% Rates", logo_url: new URL("../imgs/Sites/gamehag.png", import.meta.url).href, visit_url: "https://gamehag.com/r/netrox", rating: 5, rates: 65, offerwalls: ["revu", "torox", "lootably", "ayetstudios", "myChips", "adscend", "timewall"] },
  { name: "Freeward", description: "70-80% Rates", logo_url: new URL("../imgs/Sites/freeward.png", import.meta.url).href, visit_url: "https://freeward.net/ref/lom3w", rating: 5, rates: 80, offerwalls: ["primeearn", "torox", "ayetstudios", "adtowall", "mmwall", "lootably", "waxrewards", "myChips", "monlix", "adscend", "revu", "notik", "timewall"] },
  { name: "GG2U", description: "70-75% Rates", logo_url: new URL("../imgs/Sites/gg2u.png", import.meta.url).href, visit_url: "https://premium.gg2u.org/?referrer=netroxtv", rating: 5, rates: 75, offerwalls: [] },
  { name: "CashHut", description: "75% Rates", logo_url: new URL("../imgs/Sites/cashhut.png", import.meta.url).href, visit_url: "https://cashhut.net/ref/L7TLOG", rating: 5, rates: 75, offerwalls: ["ayetstudios", "adtowall", "lootably", "waxrewards", "notik", "timewall"] },
  { name: "SplitDrop", description: "70-75% Rates", logo_url: new URL("../imgs/Sites/splitdrop.png", import.meta.url).href, visit_url: "https://splitdrop.com/friend/74388", rating: 5, rates: 75, offerwalls: ["gemiad", "myChips", "ayetstudios", "torox", "hangmyads", "adtowall", "adgate", "mmwall", "notik", "monlix", "adscend", "lootably", "timewall", "revu"] },
  { name: "EzzCash", description: "70-75% Rates", logo_url: new URL("../imgs/Sites/ezzcash.png", import.meta.url).href, visit_url: "https://ezz.cash/?ref=netrox", rating: 5, rates: 75, offerwalls: ["ayetstudios", "lootably", "mmwall", "notik", "adtowall"] },
  { name: "CashTipay", description: "Brand New Site | A Lot of Potential", logo_url: new URL("../imgs/Sites/cashtipay.png", import.meta.url).href, visit_url: "https://cashtipay.com/register?referral=netrox", rating: 5, rates: 50, offerwalls: ["adgate", "torox"] },
  { name: "MistCash", description: "50% Rates", logo_url: "https://mistcash.co/assets/images/logo/68ab2ca2af3d6.png", visit_url: "https://mistcash.co/r/qmDcV", rating: 5, rates: 50, offerwalls: ["gemiad", "pixylabs", "hangmyads", "adtowall", "monlix", "lootably", "torox", "notik"] },
  { name: "EarnG", description: "50% Rates", logo_url: "https://earng.net/storage/uploads/logos/IVbKAuzTxXgfFhoG0JpB830PEnu4BiMQ7GbM5Uqn.png", visit_url: "https://earng.net/ref/nlDaO0d7", rating: 5, rates: 50, offerwalls: ["adtowall", "lootably", "monlix", "notik"] },
  { name: "FreeCash", description: "70-75% Rates | Instant Cashouts", logo_url: new URL("../imgs/Sites/freecash.png", import.meta.url).href, visit_url: "https://freecash.com/r/netroxx", bonus_tag: "Stake +15%", rating: 5, rates: 70, offerwalls: ["adgate", "gemiad", "lootably", "torox", "ayetstudios", "myChips", "notik", "mmwall", "revu", "monlix", "adscend"] },
  { name: "GimmeBux", description: "Low Rates | Good Leaderboards", logo_url: new URL("../imgs/Sites/gimmebux.svg", import.meta.url).href, visit_url: "https://gimmebux.com/r/netrox", bonus_tag: "Stake +15%", rating: 5, rates: 50, offerwalls: ["adgate", "lootably"] },
  { name: "GrindBux", description: "70% Rates", logo_url: new URL("../imgs/Sites/GrindBux.png", import.meta.url).href, visit_url: "https://grindbux.com/ref/netroxtv", rating: 4, rates: 70, offerwalls: ["torox", "adscend", "ayetstudios", "adtowall", "mmwall", "timewall", "lootably", "gemiad", "revu", "monlix", "hangmyads", "myChips", "notik", "waxrewards"] },
  { name: "Paidcash", description: "70% Rates", logo_url: new URL("../imgs/Sites/paidcash.png", import.meta.url).href, visit_url: "https://paidcash.co/r/ZWWEYY", rating: 4, rates: 70, offerwalls: ["adgate", "adtowall", "torox", "lootably", "myChips", "ayetstudios", "adscend", "revu"] },
  { name: "Gainify", description: "70% Rates", logo_url: new URL("../imgs/Sites/gainify.png", import.meta.url).href, visit_url: "https://gainify.net/ref/ae28248e0ce0", rating: 4, rates: 70, offerwalls: ["adgate", "adtowall", "torox", "lootably", "myChips", "ayetstudios", "adscend", "revu"] },
  { name: "Earnably", description: "70-75% Rates", logo_url: new URL("../imgs/Sites/earnably.png", import.meta.url).href, visit_url: "https://earnably.com/join/3079623", rating: 5, rates: 75, offerwalls: ["adgate", "adtowall", "torox", "lootably", "myChips", "ayetstudios", "adscend", "revu"] },
  { name: "Ysense", description: "Good Offers when boosts ONLY", logo_url: new URL("../imgs/Sites/ysense.png", import.meta.url).href, visit_url: "https://www.ysense.com/?rb=139348631", rating: 4, rates: 50, offerwalls: ["adgate", "gemiad"] },
  { name: "SwagBucks", description: "Good Offers when boosts ONLY", logo_url: new URL("../imgs/Sites/swagbucks.png", import.meta.url).href, visit_url: "https://www.swagbucks.com/p/register?rb=195191067&rp=1", rating: 4, rates: 50, offerwalls: ["adgate", "revu"] },
  { name: "KashRewards", description: "65% Rates", logo_url: new URL("../imgs/Sites/kashrewards.ico", import.meta.url).href, visit_url: "https://kashrewards.com/?a=383", rating: 4, rates: 65, offerwalls: ["lootably", "monlix", "ayetstudios", "notik", "adtowall", "timewall"] },
  { name: "Timebucks", description: "10+ Years of Activity | Fast Payouts", logo_url: new URL("../imgs/Sites/timebucks.png", import.meta.url).href, visit_url: "https://timebucks.com/?refID=225428688", rating: 5, rates: 90, offerwalls: ["adgate", "adtowall", "torox", "lootably", "myChips", "ayetstudios", "adscend", "revu", "pixylabs"] },
  { name: "NitroLoot", description: "Earn Rewards", logo_url: new URL("../imgs/Sites/nitroloot.png", import.meta.url).href, visit_url: "https://nitroloot.com/r/a5zzpc7weh", rating: 4, rates: 50, offerwalls: ["adgate", "adtowall", "torox", "lootably", "myChips", "ayetstudios", "adscend", "revu"] },
  { name: "ZemCrypto", description: "Crypto Rewards", logo_url: new URL("../imgs/Sites/zemcrypto.png", import.meta.url).href, visit_url: "https://zemcrypto.com/?a=3781", rating: 4, rates: 60, offerwalls: ["adgate", "adtowall", "torox", "lootably", "myChips", "ayetstudios", "adscend", "revu"] },
  { name: "JumpTask", description: "Earn by Completing Tasks", logo_url: new URL("../imgs/Sites/jumptask.webp", import.meta.url).href, visit_url: "https://www.jumptask.io/r/vulykapahymy", rating: 4, rates: 50, offerwalls: ["adgate", "adtowall", "torox", "lootably", "myChips", "ayetstudios", "adscend", "revu"] },
  { name: "MoneyTune", description: "Mobile Earning App", logo_url: new URL("../imgs/Sites/moneytune.png", import.meta.url).href, visit_url: "https://moneytune.page.link/o3QaXaYYsGDMwQscA", badge: "mobile_app", rating: 4, rates: 50, offerwalls: ["adgate", "adtowall", "torox", "lootably", "myChips", "ayetstudios", "adscend", "revu"] },
  { name: "Roaster Earn", description: "Mobile App", logo_url: new URL("../imgs/Sites/roasterEarn.webp", import.meta.url).href, visit_url: "https://play.google.com/store/apps/details?id=com.roaster.earn.easy", badge: "mobile_app", rating: 4, rates: 55, offerwalls: ["adgate", "adtowall", "torox", "lootably", "myChips", "ayetstudios", "adscend", "revu"] },
  { name: "FreeMoneyCoins", description: "Earn Free Coins", logo_url: new URL("../imgs/Sites/freemoneycoins.png", import.meta.url).href, visit_url: "https://freemoneycoins.com/referral/netrox", rating: 3, rates: 50, offerwalls: ["adgate", "adtowall", "torox", "lootably", "myChips", "ayetstudios", "adscend", "revu"] },
  { name: "CortalyCash", description: "Earn Rewards", logo_url: new URL("../imgs/Sites/cortalyCash.png", import.meta.url).href, visit_url: "https://cortalycash.com/ref/NetroxTV", rating: 3, rates: 50, offerwalls: ["adgate", "adtowall", "torox", "lootably", "myChips", "ayetstudios", "adscend", "revu"] },
  { name: "TurtleCash", description: "Earn Rewards", logo_url: new URL("../imgs/Sites/turtleCash.png", import.meta.url).href, visit_url: "https://turtlecash.eu/index.php?inscription&p=NetroxTTV", rating: 3, rates: 50, offerwalls: ["adgate", "adtowall", "torox", "lootably", "myChips", "ayetstudios", "adscend", "revu"] },
  { name: "GaintPlay", description: "60% Rates", logo_url: new URL("../imgs/Sites/gaintplay.png", import.meta.url).href, visit_url: "https://gaintplay.com/refer/netrox", rating: 3, rates: 60, offerwalls: ["torox", "gemiad", "adscend", "lootably", "hangmyads", "revu", "notik", "timewall"] },
  { name: "WeCash", description: "60% Rates", logo_url: new URL("../imgs/Sites/wecash.png", import.meta.url).href, visit_url: "https://wecash.one/?inviteCode=iEnuXi6cT7MyzTUqGuqp", rating: 3, rates: 60, offerwalls: ["torox", "ayetstudios", "adgate", "lootably", "adscend", "mmwall", "timewall", "monlix", "notik", "myChips"] },
  { name: "EasyBucks", description: "60% Rates", logo_url: new URL("../imgs/Sites/easybucks.png", import.meta.url).href, visit_url: "https://www.easybucks.app/?rb=160502816", rating: 3, rates: 60, offerwalls: ["adgate", "adtowall", "torox", "lootably", "myChips", "ayetstudios", "adscend", "revu"] },
];

export const otherSites = allSites;


