// All GPT sites data
export const featuredSites = [
  {
    name: "Earnlab",
    tagline: "Highest paying GPT site with multiple offerwalls",
    bonus: "Gamdom +25% — Use code NETROX",
    logo_url: "https://www.gpt-sites.com/imgs/earnlab.png",
    visit_url: "https://earnlab.com/r/netrox",
    bonus_tag: "Gamdom +25%",
    rank: 1,
    rating: 5,
    features: ["Instant payments", "Sign up bonus", "Referral program", "Worldwide"],
    details: { pay_time: "A few minutes", min_withdraw: "$0.50", min_age: "18" },
    rewards: ["PayPal", "Bitcoin", "Litecoin", "Gift Cards"],
  },
  {
    name: "CashInStyle",
    tagline: "$2 bonus after earning $10",
    logo_url: "https://www.gpt-sites.com/imgs/cis.svg",
    visit_url: "https://cashinstyle.com/?ref=NETROX",
    rank: 2,
    rating: 5,
    features: ["Instant payments", "Sign up bonus", "Referral program", "Worldwide"],
    details: { pay_time: "24 hours", min_withdraw: "$2.00", min_age: "13" },
    rewards: ["PayPal", "Bitcoin", "Litecoin"],
  },
  {
    name: "GemsLoot",
    tagline: "Receive up to four free cases!",
    logo_url: "https://www.gpt-sites.com/imgs/gemsloot.jpg",
    visit_url: "https://gemsloot.com/?aff=netrox",
    bonus_tag: "Roobet +20%",
    rank: 3,
    rating: 5,
    features: ["Instant payments", "Sign up bonus", "Referral program", "Worldwide"],
    details: { pay_time: "Within 12 hours", min_withdraw: "$0.50", min_age: "16" },
    rewards: ["PayPal", "Bitcoin", "Litecoin", "Amazon"],
  },
  {
    name: "Earnopolis",
    tagline: "95% Rates — Fast cashouts & exclusive offers",
    logo_url: "https://www.gpt-sites.com/imgs/earnopolis.webp",
    visit_url: "https://earnopolis.com/r/?r=netrox",
    rank: 4,
    rating: 4,
    features: ["Fast payments", "Sign up bonus", "Referral program", "Worldwide"],
    details: { pay_time: "1-3 hours", min_withdraw: "$1.00", min_age: "16" },
    rewards: ["PayPal", "Bitcoin", "Gift Cards"],
  },
];

export const otherSites = [
  { name: "MoonMiles", description: "80% Rates | Fast Cashouts", logo_url: "https://www.gpt-sites.com/imgs/moonmiles.png", visit_url: "https://moonmiles.io/r/netrox", badge: "new", rating: 5 },
  { name: "Pengu Pace", description: "Exclusive Offers | Instant Cashout", logo_url: "https://www.gpt-sites.com/imgs/pengu.png", visit_url: "https://go.scrambly.io/kPE2RU", badge: "mobile_app", rating: 5 },
  { name: "Scrambly", description: "Exclusive Offers | Instant Cashout", logo_url: "https://www.gpt-sites.com/imgs/scrambly_%20logo.jpg", visit_url: "https://go.scrambly.io/ao1aoE", badge: "mobile_app", rating: 5 },
  { name: "RewardFlow", description: "New GPT Site | Multiple Offerwalls", logo_url: "https://www.gpt-sites.com/imgs/rewardflow.png", visit_url: "https://rewardflow.me/?ref=NETROX", badge: "new", rating: 5 },
  { name: "CoinPayU", description: "80-85% Rates | High Site Bonuses", logo_url: "https://www.gpt-sites.com/imgs/coinpayu.gif", visit_url: "https://www.coinpayu.com/?r=Netrox", badge: "popular", rating: 5 },
  { name: "CashTask", description: "85% Rates on Offerwalls | Instant Cashouts", logo_url: "https://www.gpt-sites.com/imgs/cashtask.webp", visit_url: "https://cashtask.net/r/47CWX93", badge: "popular", rating: 5 },
  { name: "Chequity", description: "80% Rates | Simple Website", logo_url: "https://www.gpt-sites.com/imgs/cheq.png", visit_url: "https://chequity.io/r/128BDC40", badge: "popular", bonus_tag: "Clash.gg +25%", rating: 5 },
  { name: "CashEarn", description: "80% Rates on Offerwalls", logo_url: "https://www.gpt-sites.com/imgs/cashearn.webp", visit_url: "https://cashearn.gg/r/8L3D1M7", badge: "popular", rating: 5 },
  { name: "EarnLoop", description: "85% Rates | Fast Cashouts", logo_url: "https://www.gpt-sites.com/imgs/earnloop.svg", visit_url: "https://earnloop.net/r/YLNMXR5KWR", rating: 5 },
  { name: "RBXFast", description: "80% Rates", logo_url: "https://www.gpt-sites.com/imgs/rbxfast.webp", visit_url: "https://rbxfast.com/r/netrox", rating: 5 },
  { name: "Gain.gg", description: "70-80% Rates | Instant Cashouts", logo_url: "https://www.gpt-sites.com/imgs/gain.png", visit_url: "https://gain.gg/r/netrox", rating: 5 },
  { name: "CashTipay", description: "Brand New Site | A Lot of Potential", logo_url: "https://www.gpt-sites.com/imgs/cashtipay.png", visit_url: "https://cashtipay.com/register?referral=netrox", rating: 5 },
  { name: "EzzCash", description: "70-75% Rates", logo_url: "https://www.gpt-sites.com/imgs/ezzcash.png", visit_url: "https://ezz.cash/?ref=netrox", rating: 5 },
  { name: "FreeCash", description: "70-75% Rates | Instant Cashouts", logo_url: "https://www.gpt-sites.com/imgs/freecash.png", visit_url: "https://freecash.com/r/netroxx", bonus_tag: "Stake +15%", rating: 5 },
  { name: "GimmeBux", description: "Low Rates | Good Leaderboards", logo_url: "https://www.gpt-sites.com/imgs/gimmebux.svg", visit_url: "https://gimmebux.com/r/netrox", bonus_tag: "Stake +15%", rating: 5 },
  { name: "Ysense", description: "Good Offers when boosts ONLY", logo_url: "https://www.gpt-sites.com/imgs/ysense.png", visit_url: "https://www.ysense.com/?rb=139348631", rating: 4 },
  { name: "SwagBucks", description: "Good Offers when boosts ONLY", logo_url: "https://www.gpt-sites.com/imgs/swagbucks.png", visit_url: "https://www.swagbucks.com/p/register?rb=195191067&rp=1", rating: 4 },
  { name: "FastAsk", description: "100% Rates on WaxRewards", logo_url: "https://www.gpt-sites.com/imgs/fastask.png", visit_url: "https://fastask.net/?ref=296", rating: 5 },
  { name: "SplitDrop", description: "70-75% Rates", logo_url: "https://www.gpt-sites.com/imgs/splitdrop.png", visit_url: "https://splitdrop.com/friend/74388", rating: 5 },
  { name: "GameHag", description: "80% Rates", logo_url: "https://www.gpt-sites.com/imgs/gamehag.png", visit_url: "https://gamehag.com/r/netrox", bonus_tag: "Clash.gg +25%", rating: 5 },
  { name: "KashRewards", description: "65% Rates", logo_url: "https://www.gpt-sites.com/imgs/kashrewards.ico", visit_url: "https://kashrewards.com/?a=383", rating: 4 },
  { name: "GG2U", description: "70-75% Rates", logo_url: "https://www.gpt-sites.com/imgs/gg2u.png", visit_url: "https://premium.gg2u.org/?referrer=netroxtv", rating: 5 },
  { name: "Freeward", description: "70-80% Rates", logo_url: "https://www.gpt-sites.com/imgs/freeward.png", visit_url: "https://freeward.net/ref/lom3w", rating: 5 },
  { name: "CashHut", description: "75% Rates", logo_url: "https://www.gpt-sites.com/imgs/cashhut.png", visit_url: "https://cashhut.net/ref/L7TLOG", rating: 5 },
  { name: "GrindBux", description: "70% Rates", logo_url: "https://www.gpt-sites.com/imgs/GrindBux.png", visit_url: "https://grindbux.com/ref/netroxtv", rating: 4 },
  { name: "WeCash", description: "60% Rates", logo_url: "https://www.gpt-sites.com/imgs/wecash.png", visit_url: "https://wecash.one/?inviteCode=iEnuXi6cT7MyzTUqGuqp", rating: 3 },
  { name: "Earnably", description: "70-75% Rates", logo_url: "https://www.gpt-sites.com/imgs/earnably.png", visit_url: "https://earnably.com/join/3079623", rating: 5 },
  { name: "GaintPlay", description: "60% Rates", logo_url: "https://www.gpt-sites.com/imgs/gaintplay.png", visit_url: "https://gaintplay.com/refer/netrox", rating: 3 },
  { name: "Paidcash", description: "70% Rates", logo_url: "https://www.gpt-sites.com/imgs/paidcash.png", visit_url: "https://paidcash.co/r/ZWWEYY", rating: 4 },
  { name: "Giftably", description: "80% Rates", logo_url: "https://www.gpt-sites.com/imgs/giftably.webp", visit_url: "https://giftably.net/login/Lucas", rating: 5 },
  { name: "RewardXP", description: "80% Rates", logo_url: "https://www.gpt-sites.com/imgs/rewardxp.png", visit_url: "https://www.rewardxp.com/join/1425421", rating: 5 },
  { name: "PrizeBear", description: "80% Rates", logo_url: "https://www.gpt-sites.com/imgs/prizebear.png", visit_url: "https://prizebear.com/r/uWEzvO", rating: 5 },
  { name: "Gainify", description: "70% Rates", logo_url: "https://www.gpt-sites.com/imgs/gainify.png", visit_url: "https://gainify.net/ref/ae28248e0ce0", rating: 4 },
  { name: "Sparkvey", description: "80% Rates", logo_url: "https://www.gpt-sites.com/imgs/sparkvey.ico", visit_url: "https://sparkvey.com/?ref=netrox", rating: 5 },
  { name: "EasyBucks", description: "60% Rates", logo_url: "https://www.gpt-sites.com/imgs/easybucks.png", visit_url: "https://www.easybucks.app/?rb=160502816", rating: 3 },
  { name: "Timebucks", description: "10+ Years of Activity | Fast Payouts", logo_url: "https://www.gpt-sites.com/imgs/timebucks.png", visit_url: "https://timebucks.com/?refID=225428688", rating: 5 },
  { name: "BambooRush", description: "70% Rates", logo_url: "https://www.gpt-sites.com/imgs/bamboorushLogo.webp", visit_url: "https://bamboorush.com/?r=netrox", rating: 4 },
  { name: "NitroLoot", description: "Earn Rewards", logo_url: "https://www.gpt-sites.com/imgs/nitroloot.png", visit_url: "https://nitroloot.com/r/a5zzpc7weh", rating: 4 },
  { name: "ZemCrypto", description: "Crypto Rewards", logo_url: "https://www.gpt-sites.com/imgs/zemcrypto.png", visit_url: "https://zemcrypto.com/?a=3781", rating: 4 },
  { name: "JumpTask", description: "Earn by Completing Tasks", logo_url: "https://www.gpt-sites.com/imgs/jumptask.webp", visit_url: "https://www.jumptask.io/r/vulykapahymy", rating: 4 },
  { name: "MoneyTune", description: "Mobile Earning App", logo_url: "https://www.gpt-sites.com/imgs/moneytune.png", visit_url: "https://moneytune.page.link/o3QaXaYYsGDMwQscA", badge: "mobile_app", rating: 4 },
  { name: "Roaster Earn", description: "Mobile App", logo_url: "https://www.gpt-sites.com/imgs/roasterEarn.webp", visit_url: "https://play.google.com/store/apps/details?id=com.roaster.earn.easy", badge: "mobile_app", rating: 4 },
  { name: "FreeMoneyCoins", description: "Earn Free Coins", logo_url: "https://www.gpt-sites.com/imgs/freemoneycoins.png", visit_url: "https://freemoneycoins.com/referral/netrox", rating: 3 },
  { name: "CortalyCash", description: "Earn Rewards", logo_url: "https://www.gpt-sites.com/imgs/cortalyCash.png", visit_url: "https://cortalycash.com/ref/NetroxTV", rating: 3 },
  { name: "TurtleCash", description: "Earn Rewards", logo_url: "https://www.gpt-sites.com/imgs/turtleCash.png", visit_url: "https://turtlecash.eu/index.php?inscription&p=NetroxTTV", rating: 3 },
];